import Sprockell
prog :: [Instruction]
prog = [
    Load (ImmValue 0) regA,
    WriteInstr regA (DirAddr 0),
    ReadInstr (IndAddr regSprID),
    Receive regA,
    Compute Equal regSprID reg0 regB,
    Branch regB (Rel 4),
    Compute NEq regA regSprID regB,
    Branch regB (Ind regA),
    Jump (Rel (-6)),
    Load (ImmValue 5) regA,
    Store regA (DirAddr 0),
    Load (ImmValue 1) regA,
    Store regA (DirAddr 1),
    Load (DirAddr 1) regA,
    Compute Equal regA reg0 regA,
    Branch regA (Rel 6),
    Load (ImmValue 3) regA,
    Store regA (DirAddr 2),
    Load (DirAddr 2) regA,
    WriteInstr regA numberIO,
    Jump (Rel 1),
    Load (DirAddr 0) regA,
    WriteInstr regA numberIO,
    Load (DirAddr 1) regA,
    Compute Equal regA reg0 regA,
    Branch regA (Rel 4),
    Load (ImmValue 12) regA,
    Store regA (DirAddr 0),
    Jump (Rel 1),
    Load (DirAddr 0) regA,
    WriteInstr regA numberIO,
    Load (ImmValue 6) regA,
    Store regA (DirAddr 0),
    Compute Add reg0 regPC regA,
    Compute Equal regSprID reg0 regB,
    Branch regB (Rel 2),
    EndProg,
    EndProg]
main = run [prog]
